-- King & Angel platform schema
-- Project: PKU Loving Society · Loving Journey 2026 · Fujian Yongchun Road

create extension if not exists pgcrypto;

create table if not exists public.activity_settings (
  id bigint primary key generated by default as identity,
  activity_title text not null default '北大爱心社｜爱心万里行 2026 福建永春路',
  location_label text not null default '福建永春路',
  activity_ended boolean not null default false,
  current_round integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.invites (
  code text primary key,
  display_name text not null,
  can_admin boolean not null default false,
  email text,
  claimed_by uuid unique,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  can_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.wishes (
  id bigint primary key generated always as identity,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  content text not null,
  is_locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wishes_content_length check (char_length(trim(content)) between 1 and 200)
);

create table if not exists public.king_assignments (
  angel_user_id uuid primary key references public.profiles(id) on delete cascade,
  king_user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint king_assignment_not_self check (angel_user_id <> king_user_id)
);

create table if not exists public.task_templates (
  id bigint primary key generated always as identity,
  title text not null,
  description text not null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.task_rounds (
  id bigint primary key generated always as identity,
  round_no integer not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.task_assignments (
  id bigint primary key generated always as identity,
  round_id bigint not null references public.task_rounds(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  task_template_id bigint not null references public.task_templates(id) on delete cascade,
  completed boolean not null default false,
  assigned_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (round_id, user_id)
);

create table if not exists public.task_submissions (
  id bigint primary key generated always as identity,
  task_assignment_id bigint not null unique references public.task_assignments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.anonymous_messages (
  id bigint primary key generated always as identity,
  from_user_id uuid not null references public.profiles(id) on delete cascade,
  to_user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.activity_settings enable row level security;
alter table public.invites enable row level security;
alter table public.profiles enable row level security;
alter table public.wishes enable row level security;
alter table public.king_assignments enable row level security;
alter table public.task_templates enable row level security;
alter table public.task_rounds enable row level security;
alter table public.task_assignments enable row level security;
alter table public.task_submissions enable row level security;
alter table public.anonymous_messages enable row level security;

drop policy if exists "read own profile" on public.profiles;
create policy "read own profile"
on public.profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "read own wish" on public.wishes;
create policy "read own wish"
on public.wishes
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "read own king assignment" on public.king_assignments;
create policy "read own king assignment"
on public.king_assignments
for select
to authenticated
using (angel_user_id = auth.uid());

drop policy if exists "read own task assignments" on public.task_assignments;
create policy "read own task assignments"
on public.task_assignments
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "read own task submissions" on public.task_submissions;
create policy "read own task submissions"
on public.task_submissions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "read own received messages" on public.anonymous_messages;
create policy "read own received messages"
on public.anonymous_messages
for select
to authenticated
using (to_user_id = auth.uid());

drop policy if exists "read own sent messages" on public.anonymous_messages;
create policy "read own sent messages"
on public.anonymous_messages
for select
to authenticated
using (from_user_id = auth.uid());

insert into public.activity_settings (id, activity_title, location_label, activity_ended, current_round)
values (1, '北大爱心社｜爱心万里行 2026 福建永春路', '福建永春路', false, 0)
on conflict (id) do update
set activity_title = excluded.activity_title,
    location_label = excluded.location_label;

-- Replace these example codes before正式使用
insert into public.invites (code, display_name, can_admin)
values
  ('ADMIN', '文建负责人', true),
  ('A1001', '张三', false),
  ('A1002', '李四', false),
  ('A1003', '王五', false)
on conflict (code) do nothing;
